### PR TITLE
next branch

### PR DESCRIPTION
**Pull request by mrhota**

### CODE REVIEW

**Comment by jan-hudec** [comment]
@mrhota, you think it's about time to put it in master, or did you just create it for tracking?

From the infrastructure part, I think the only missing thing is LanguageTag matching (needed to find which data set from CLDR/message catalog to use) and an auxiliary function for finding “subfacets” so we can have a `Data` subfacet providing CLDR (or system) data for all categories and the facets implementing the logic on top of it.

And then question is how many facets we should implement. I thought about doing at least the two that somehow exist in the old version, but if we are going to drop all compatibility, it does not matter.

Plus we should set up GitHub Pages (https://rust-locale.github.io/) with documentation.

**Comment by mrhota** [comment]
just for tracking. it's easier to see what's going on, and the comments are
printed in the pr.

**Comment by jan-hudec** [comment]
@mrhota wrote:

> just for tracking.

Ok.

I pushed the `facet::try_get_by_tag` and the RFC4647 (mostly) tag matching. That should be good enough to let us move ahead to some facets.

**Comment by mrhota** [comment]
We should remove all the `LanguageTag` code. There is a crate called `language-tags` on crates.io. It's used by `hyper` and does what we need. Anything `language-tags` lacks can be added to it via PR.

**Comment by jan-hudec** [comment]
@mrhota, damn, and this time it's been _our_ mistake, because it existed at the time we discussed the design.

**Comment by jan-hudec** [comment]
For reference, a [github link](https://github.com/pyfisch/rust-language-tags) and [cargo link](https://crates.io/crates/language-tags).

I don't really like the overhead. Most tags will be just a couple of bytes long strings, that can often just be borrowed from somewhere, but this structure is a beast of `Option<String>`s and `Vec<String>`s that will take many times more bytes in pointers and metadata than there is actual data. A huge overkill when most of the time all that is needed is to borrow the tag from the `Locale` and use it as a hash key in some cache.

It does support canonicalization though, so we should probably make use of it for the places where we need to actually interpret the tags.

**Comment by mrhota** [comment]
@jan-hudec I think questions of overhead are premature since we don't even have a working library. If we need to optimize `LanguageTags`, we can issue a PR. We don't have to reinvent the wheel here; this project and `hyper` stand to benefit by using and improving that lib.

**Comment by jan-hudec** [comment]
I didn't say I don't want to use it. I only said I want to use the string as hash key, which is by far the most common use of the tags.

**Comment by jan-hudec** [comment]
@mrhota, hm, there might be one more problem with the locale-core dependency on language-tags: we need `locale` to be able to always depend on latest `locale-core` by making sure the interface of `locale-core` is highly stable. But if we reexport `language-tags` types an incompatible update in that could break things. That still does not mean I would be against using it, just saying that we'll have to be somewhat careful about the API.

**Comment by jan-hudec** [comment]
Partially scratching in favor of using https://github.com/rust-locale/icu-sys as a backend; closing.

**Pull request closed without merging**
